name: Sync Upstream

env:
  UPSTREAM_URL: "https://github.com/j-hc/revanced-magisk-module.git"
  WORKFLOW_TOKEN: ${{ secrets.PAT_TOKEN }}
  UPSTREAM_BRANCH: "main"
  DOWNSTREAM_BRANCH: "main"

on:
  schedule:
    - cron: '0 13 * * *' 
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.DOWNSTREAM_BRANCH }}
         
      - name: Fetch Upstream
        run: |
          git remote add upstream ${{ env.UPSTREAM_URL }}
          git fetch upstream ${{ env.UPSTREAM_BRANCH }}
    
      - name: Merge Upstream Changes
        run: |
          git merge upstream/${{ env.UPSTREAM_BRANCH }} || true
        continue-on-error: true
    
      - name: Configure Git User
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Check for Conflicts
        run: |
          if git ls-files -u | grep .; then
            echo "Conflict detected! Conflicting files:";
            exit 1;
          else
            echo "No conflicts detected.";
          fi
          
      - name: Commit Changes
        run: |
          git add .
          git commit -m "Sync with upstream" || echo "No changes to commit."
      
      - name: Update Remote URL
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/pembotol/rvx-personal-taste.git

      - name: Push Changes
        run: git push origin ${{ env.DOWNSTREAM_BRANCH }}
